"""Emit `research/CLAUDE-PAPER-CONTEXT.md` — the per-paper context fragment.

Read by the SessionStart hook (`scripts/session-start.sh`) on every Claude
Code session that opens in a directory containing a compiled `research/`.
The hook inlines this file into the initial system prompt so Claude sees
paper-specific routing hints, atom counts by category, open assumptions,
and source coverage without making any tool calls.

Generated by the CLI at compile + ingest time. Domain-neutral: works for
ML, physics, chemistry, biology, etc.; the category vocabulary follows the
v1.0 de-bias pass (`method`, `objective`, `data`, `procedure`, `parameter`,
`evaluation`, `baseline`, `theory`).
"""

from __future__ import annotations

import time
from collections import Counter
from pathlib import Path
from typing import Any

from ..atoms import Atom
from ..ir import Paper


# Cross-domain field detection. Counts atom categories vs broad buckets so
# the field hint stays useful for ML / physics / chem / bio papers without
# hardcoding any field-specific term.
def _field_hint(by_category: Counter) -> str:
    n_method = by_category.get("method", 0)
    n_objective = by_category.get("objective", 0)
    n_data = by_category.get("data", 0)
    n_procedure = by_category.get("procedure", 0)
    n_theory = by_category.get("theory", 0)
    n_total = sum(by_category.values()) or 1

    if n_theory >= max(n_method, n_objective, n_data):
        return "Theory-heavy paper. Expect more `theorem` / `assumption` atoms than code-level ones."
    if n_method > 0 and n_procedure > 0 and n_data > 0:
        return "Implementation-shaped paper. The corpus has methods + procedures + data — code-level reproduction is plausible."
    if n_data >= 2 * (n_method + n_procedure):
        return "Data-heavy paper (corpus / measurements / cohort dominant). Implementation may be light."
    if n_method >= 5 and n_procedure == 0:
        return "Architecture-/method-heavy paper. Limited `procedure` atoms — the paper may delegate training/run details to a cited reference."
    return f"Mixed corpus: {n_method} method, {n_objective} objective, {n_data} data, {n_procedure} procedure, {n_theory} theory atoms."


def _routing_hints(by_category: Counter, neighborhood_papers: int) -> list[str]:
    """Sub-skill hints based on what's in the corpus. Domain-neutral."""
    hints: list[str] = []
    if by_category.get("method", 0) >= 5:
        hints.append(
            "Method atoms dominant → `/paper-compiler:use-research-context implement-method`. "
            "Use `query(...mode='local')` for entity lookups (encoder / scheme / route)."
        )
    if by_category.get("objective", 0) >= 1:
        hints.append(
            "`implement-objective` covers loss / Hamiltonian / yield / fitness. "
            "`equation_lookup` returns hits for objective-side math."
        )
    if by_category.get("procedure", 0) >= 1:
        hints.append(
            "`implement-procedure` covers training loop / integrator / experimental protocol. "
            "Parameter values often live in tables — use `query_chunks(prefer_kind='table')`."
        )
    if by_category.get("evaluation", 0) >= 1:
        hints.append(
            "`implement-evaluation` covers metrics / diagnostics / statistical tests."
        )
    if by_category.get("baseline", 0) >= 1:
        hints.append(
            "`implement-baseline` for published comparisons. `citation_neighbors(role='baseline_dependency')` returns the set."
        )
    if neighborhood_papers >= 30:
        hints.append(
            f"Large neighborhood ({neighborhood_papers} papers) — `query(..., mode='global')` is effective for "
            "thematic / survey questions; communities are well-populated."
        )
    return hints


def render_paper_context(
    target: Paper,
    atoms: list[Atom],
    graph_doc: dict[str, Any],
    missing_details: list[Any],
    neighborhood_stats: dict[str, Any],
) -> str:
    """Build the markdown fragment.

    Inputs come from the compile pipeline. Output is ≤ ~60 lines so the
    SessionStart hook can inline it cheaply.
    """
    title = (target.metadata.title or "untitled").strip()
    paper_id = target.paper_id

    # Atom counts by category (domain-neutral).
    by_category: Counter = Counter(a.category for a in atoms if a.category)

    # Sub-category breakdown — only emit lines for categories with atoms.
    sub_lines: list[str] = []
    for cat in ("method", "objective", "data", "preprocessing", "procedure",
                "parameter", "evaluation", "baseline", "theory"):
        n = by_category.get(cat, 0)
        if n > 0:
            sub_lines.append(f"  - `{cat}`: {n}")

    # Source breakdown (Phase 3 papers_by_source).
    by_source = neighborhood_stats.get("papers_by_source") or {}
    source_lines: list[str] = []
    if by_source:
        for src, n in sorted(by_source.items(), key=lambda kv: -kv[1]):
            source_lines.append(f"  - `{src}`: {n}")
    else:
        source_lines.append("  - _(not recorded; v0.2 artifact predates Phase 3 multi-source tracking)_")

    # Open assumptions — short list (top 5). Accepts either dataclass-like
    # objects (cli IR) or plain dicts (parsed JSON).
    md_lines: list[str] = []
    for md in (missing_details or [])[:5]:
        if isinstance(md, dict):
            q = md.get("question") or ""
            cat = md.get("category") or "?"
        else:
            q = getattr(md, "question", "") or ""
            cat = getattr(md, "category", "") or "?"
        if q:
            md_lines.append(f"  - **{cat}**: {q}")
    if not md_lines:
        md_lines.append("  - _(none — `list_missing_details()` for the live list)_")

    n_papers = (neighborhood_stats.get("papers_seen") or
                neighborhood_stats.get("papers_in_neighborhood") or 0)
    n_acquired = neighborhood_stats.get("papers_acquired", 0)
    coverage_pct = neighborhood_stats.get("coverage_pct")  # may live in build-manifest only
    field_hint = _field_hint(by_category)
    routing_hints = _routing_hints(by_category, n_papers)

    timestamp = time.strftime("%Y-%m-%dT%H:%MZ", time.gmtime())

    lines: list[str] = []
    lines.append(f"# Paper context — {title}")
    lines.append(f"")
    lines.append(f"**Paper ID:** `{paper_id}`")
    lines.append(f"**Compiled at:** {timestamp}")
    lines.append(f"")
    lines.append("## Field & shape")
    lines.append(f"- {field_hint}")
    lines.append(f"- Atoms total: **{sum(by_category.values())}** "
                 f"across {len(by_category)} categories.")
    lines.append(f"- Neighborhood: **{n_papers}** papers ({n_acquired} acquired)."
                 + (f" Coverage: {coverage_pct}%." if coverage_pct is not None else ""))
    lines.append("")
    lines.append("## Atom categories present")
    lines.extend(sub_lines if sub_lines else ["  - _(empty corpus)_"])
    lines.append("")
    lines.append("## Routing hints")
    for h in routing_hints:
        lines.append(f"- {h}")
    if not routing_hints:
        lines.append("- Mixed corpus — let `route_query_only(<question>)` pick the mode.")
    lines.append("")
    lines.append("## Open assumptions (top 5)")
    lines.extend(md_lines)
    lines.append("")
    lines.append("## Source coverage")
    lines.extend(source_lines)
    lines.append("")
    lines.append("## Hard rules (enforced via PreToolUse hook)")
    lines.append("- **MCP-only access** to atoms / evidence / graph / DB. "
                 "Direct `Read`/`Glob`/`Grep` on `research/wiki/atoms/`, "
                 "`research/wiki/papers/`, `research/wiki/communities/`, "
                 "`research/evidence/`, `research/graph.json`, "
                 "`research/research.db` is **blocked by plugin policy**.")
    lines.append("- Start any implementation/audit work with `get_paper_context()`. "
                 "Bootstrap reads of `research/research.md` are unnecessary — "
                 "this fragment already inlines the structured summary.")
    lines.append("- Cite `atom_uid` (Phase 1 stable id) in code comments, "
                 "not the sequential `atom_id` (reshuffles on rebuild).")
    lines.append("- Significant choices / gotchas → `record_decision(...)` "
                 "(ask-gated). Lives in `research/decisions.md` and is visible to future sessions.")
    return "\n".join(lines) + "\n"


def write_paper_context(
    path: Path,
    target: Paper,
    atoms: list[Atom],
    graph_doc: dict[str, Any],
    missing_details: list[Any],
    neighborhood_stats: dict[str, Any],
) -> None:
    md = render_paper_context(target, atoms, graph_doc, missing_details, neighborhood_stats)
    path.write_text(md, encoding="utf-8")
