#!/usr/bin/env bash
# adjust-research-dir.sh
#
# Copy a compiled research/ artifact from one repo to another, write the
# target's .mcp.json so the MCP server resolves to the new location, and
# initialize empty memory dirs.
#
# Usage:  adjust-research-dir.sh <source> <target>
#
# <source> may point at a repo root containing research/ OR at the research/
# directory directly. Same for <target>: it's always the repo root.
#
# Exit codes:
#   0  success
#   1  source missing / not a research/ artifact
#   2  target already has a non-empty research/ for a different paper
#      (multi-paper-per-repo is out of scope for v2.0)

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: adjust-research-dir.sh <source> <target>" >&2
  exit 1
fi

source_arg="$1"
target_arg="$2"

# Resolve source -> research/ directory
if [[ -f "$source_arg/build-manifest.json" ]]; then
  source_dir="$source_arg"
elif [[ -f "$source_arg/research/build-manifest.json" ]]; then
  source_dir="$source_arg/research"
else
  echo "FAIL: $source_arg does not look like a research/ artifact (no build-manifest.json)" >&2
  exit 1
fi

if [[ ! -d "$target_arg" ]]; then
  mkdir -p "$target_arg"
fi
target_research="$target_arg/research"

# Refuse to clobber a different paper's artifact in the target.
if [[ -f "$target_research/build-manifest.json" ]]; then
  src_id="$(jq -r '.target_paper_id // empty' "$source_dir/build-manifest.json" 2>/dev/null || true)"
  tgt_id="$(jq -r '.target_paper_id // empty' "$target_research/build-manifest.json" 2>/dev/null || true)"
  if [[ -n "$tgt_id" && "$src_id" != "$tgt_id" ]]; then
    echo "FAIL: $target_research already contains a different paper ($tgt_id vs $src_id). Multi-paper-per-repo is out of scope for v2.0. Either remove the target's research/ or pick a different target." >&2
    exit 2
  fi
  echo "INFO: target already has research/ for the SAME paper; refreshing in place" >&2
fi

# Copy
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete --exclude='.git' "$source_dir/" "$target_research/"
else
  rm -rf "$target_research"
  mkdir -p "$target_research"
  cp -R "$source_dir/." "$target_research/"
fi

# Memory dirs that should always exist post-port.
mkdir -p "$target_research/sessions"

# Touch decisions.md so PostToolUse/Stop hooks can write to it.
if [[ ! -f "$target_research/decisions.md" ]]; then
  cat > "$target_research/decisions.md" <<'EOF'
# Decisions & Gotchas

Append-only. Written by `mcp__paper-compiler__record_decision`.

EOF
fi

# Append a port event to wiki/log.md (the canonical event log).
if [[ -f "$target_research/wiki/log.md" ]]; then
  iso="$(date -u +%Y-%m-%dT%H:%MZ)"
  printf '\n## %s — port\n- source: %s\n- target: %s\n' \
    "$iso" "$source_dir" "$target_research" >> "$target_research/wiki/log.md"
fi

# Write/update target's .mcp.json so MCP server points at the new location.
mkdir -p "$target_arg"
mcp_json="$target_arg/.mcp.json"
if [[ ! -f "$mcp_json" ]]; then
  # Standard plugin .mcp.json template
  cat > "$mcp_json" <<EOF
{
  "_comment": "Generated by paper-compiler:use-research-context port. Points the MCP server at this repo's research/ dir.",
  "mcpServers": {
    "paper-compiler": {
      "command": "python",
      "args": ["-m", "paper_compiler_mcp.server"],
      "env": {
        "PYTHONPATH": "\${CLAUDE_PLUGIN_ROOT}/server/src",
        "PAPER_COMPILER_RESEARCH_DIR": "$target_research"
      }
    }
  }
}
EOF
else
  # If a .mcp.json exists, patch the env var in place (best-effort jq).
  if command -v jq >/dev/null 2>&1; then
    tmp="$(mktemp)"
    jq --arg dir "$target_research" \
      '.mcpServers["paper-compiler"].env.PAPER_COMPILER_RESEARCH_DIR = $dir' \
      "$mcp_json" > "$tmp" 2>/dev/null && mv "$tmp" "$mcp_json" || rm -f "$tmp"
  fi
fi

printf '{"ok":true,"source":"%s","target":"%s","mcp_json":"%s"}\n' \
  "$source_dir" "$target_research" "$mcp_json"

exit 0
